# base image
FROM artifacts-test.gwl.bz:18080/nginx:1.13.9-alpine

# add `/usr/src/app/node_modules/.bin` to $PATH
#ENV PATH /usr/src/app/node_modules/.bin:$PATH

# copy artifact build from the 'build environment'
COPY ./dist/mayhem /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]