# base image
FROM artifacts-test.gwl.bz:18080/iws/mayhem-fe-chrome

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install dependencies
# COPY package.json /usr/src/app
# RUN yarn install
# RUN yarn global add @angular/cli@6.1.4

# Copy source code
COPY . /usr/src/app

# Unit tests
RUN yarn test-prod
# E2E, scoping out of MVB
#RUN yarn e2e
# Lint
RUN yarn lint